# Security Configuration (Auto-generated)
# Do not modify manually

SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
PERMANENT_SESSION_LIFETIME = 28800
WTF_CSRF_ENABLED = True
WTF_CSRF_TIME_LIMIT = 3600
SQLALCHEMY_ECHO = False
